# Generated by Django 4.0.4 on 2022-04-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationgoal',
            name='goaltitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteergoal',
            name='goaltitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
