# Generated by Django 4.0.4 on 2022-04-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0003_rename_interval_donationgoal_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteergoal',
            old_name='Interval',
            new_name='interval',
        ),
    ]
