# Generated by Django 4.0.4 on 2022-04-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0006_alter_donationrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecord',
            name='donationreceipt',
            field=models.ImageField(blank=True, null=True, upload_to='reciepts'),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='volunteerreceipt',
            field=models.ImageField(blank=True, null=True, upload_to='reciepts'),
        ),
    ]
