# Generated by Django 4.0.4 on 2022-04-23 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0007_alter_donationrecord_donationreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duser', to=settings.AUTH_USER_MODEL),
        ),
    ]
