# Generated by Django 4.0.4 on 2022-04-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0010_alter_donationrecord_donationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_income',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationrecord',
            name='donationrecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drecord', to='charitable.donationgoal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='volunteerrecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vrecord', to='charitable.volunteergoal'),
        ),
    ]
