# Generated by Django 4.0.4 on 2022-04-26 18:32

import charitable_tracker.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0013_remove_user_annual_income_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrecord',
            name='donationreceipt',
        ),
        migrations.RemoveField(
            model_name='volunteerrecord',
            name='volunteerreceipt',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(storage=charitable_tracker.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
