# Generated by Django 4.0.4 on 2022-04-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0016_volunteerrecord_user_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailreminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribe', models.BooleanField(default=True)),
                ('interval', models.CharField(blank=True, choices=[('Week', 'Week'), ('BiWeekly', 'BiWeekly'), ('Month', 'Month'), ('Year', 'Year')], max_length=200)),
            ],
        ),
    ]
