# Generated by Django 4.0.4 on 2022-04-29 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0018_emailreminder_user_emailreminder_your_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dreceipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dreceipt', to='charitable.donationrecord'),
        ),
        migrations.AddField(
            model_name='document',
            name='vreceipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vreceipt', to='charitable.volunteerrecord'),
        ),
        migrations.AddField(
            model_name='donationgoal',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='volunteergoal',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
