# Generated by Django 3.2.13 on 2022-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0019_document_dreceipt_document_vreceipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreminder',
            name='interval',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('BiWeekly', 'BiWeekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=200),
        ),
    ]
