# Generated by Django 3.2.13 on 2022-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0022_auto_20220501_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrecord',
            old_name='donationrecord',
            new_name='goal',
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
