# Generated by Django 3.2.13 on 2022-05-03 20:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0023_auto_20220503_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('dgoaltitle', models.CharField(blank=True, max_length=100)),
                ('donationgoal', models.IntegerField()),
                ('vgoaltitle', models.CharField(blank=True, max_length=100)),
                ('volunteergoal', models.IntegerField()),
                ('interval', models.CharField(blank=True, choices=[('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountdonated', models.IntegerField()),
                ('created_at', models.DateField()),
                ('hours', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('cause', models.CharField(blank=True, choices=[('Animals', 'Animals'), ('Arts Culture Humanities', 'Arts Culture Humanities'), ('Asian Rights', 'Asian Rights'), ('Black Rights', 'Black Rights'), ('Community Development', 'Community Development'), ('Education', 'Education'), ('Environmental', 'Environmental'), ('Health', 'Health'), ('Human and Civil Rights', 'Human and Civil Rights'), ('Human Services', 'Human Services'), ('International', 'International'), ('Latino Rights', 'Latino Rights'), ('Research and Public Policy', 'Research and Public Policy'), ('Religion', 'Religion'), ("Women's Rights", "Women's Rights")], max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drecord', to='charitable.goal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='donationgoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='donationrecord',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='donationrecord',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='donationrecord',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='donationrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='donationgoal',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='volunteergoal',
        ),
        migrations.RemoveField(
            model_name='volunteergoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteerrecord',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='volunteerrecord',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='volunteerrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='volunteerrecord',
            name='volunteerrecord',
        ),
        migrations.DeleteModel(
            name='Cause',
        ),
        migrations.DeleteModel(
            name='Donationgoal',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Volunteergoal',
        ),
        migrations.AlterField(
            model_name='document',
            name='dreceipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dreceipt', to='charitable.record'),
        ),
        migrations.AlterField(
            model_name='document',
            name='vreceipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vreceipt', to='charitable.record'),
        ),
        migrations.DeleteModel(
            name='Donationrecord',
        ),
        migrations.DeleteModel(
            name='Volunteerrecord',
        ),
    ]
