# Generated by Django 3.2.13 on 2022-05-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0023_auto_20220503_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailreminder',
            old_name='your_reminder',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='volunteerrecord',
            old_name='volunteerrecord',
            new_name='goal',
        ),
    ]
