# Generated by Django 3.2.13 on 2022-05-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0029_auto_20220503_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goaltitle',
            new_name='dgoaltitle',
        ),
        migrations.AddField(
            model_name='goal',
            name='vgoaltitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
