# Generated by Django 3.2.13 on 2022-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0030_auto_20220503_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='imgreciept',
            field=models.TextField(blank=True, null=True),
        ),
    ]
