# Generated by Django 3.2.13 on 2022-05-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0031_auto_20220505_2201'),
        ('charitable', '0031_record_imgreciept'),
    ]

    operations = [
    ]
