# Generated by Django 3.2.13 on 2022-05-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0028_auto_20220505_2155'),
        ('charitable', '0032_merge_0031_auto_20220505_2201_0031_record_imgreciept'),
    ]

    operations = [
    ]
