# Generated by Django 3.2.13 on 2022-05-06 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0033_causedonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgdonations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
