# Generated by Django 3.2.13 on 2022-05-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0033_merge_20220506_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailreminder',
            old_name='message',
            new_name='your_reminder',
        ),
    ]
