# Generated by Django 3.2.13 on 2022-05-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0034_rename_message_emailreminder_your_reminder'),
        ('charitable', '0036_auto_20220506_2143'),
    ]

    operations = [
    ]
