# Generated by Django 3.2.13 on 2022-05-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0037_merge_20220507_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailreminder',
            old_name='your_reminder',
            new_name='message',
        ),
    ]
