# Generated by Django 3.2.13 on 2022-05-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0038_rename_your_reminder_emailreminder_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='charitable.cause'),
        ),
    ]
