# Generated by Django 3.2.13 on 2022-05-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0040_org_one_org'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cause',
            name='one_cause',
        ),
        migrations.RemoveConstraint(
            model_name='org',
            name='one_org',
        ),
    ]
