# Generated by Django 3.2.13 on 2022-05-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0039_alter_record_cause'),
        ('charitable', '0041_auto_20220509_1835'),
    ]

    operations = [
    ]
