# Generated by Django 3.2.13 on 2022-05-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0042_merge_0039_alter_record_cause_0041_auto_20220509_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='cause',
        ),
    ]
