# Generated by Django 3.2.13 on 2022-05-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitable', '0043_alter_record_cause'),
        ('charitable', '0044_record_cause'),
    ]

    operations = [
    ]
